language: node_js
node_js:
- '0.11'
after_success:
- chmod 600 deploy_staging_rsa
- ssh-add deploy_staging_rsa
- git remote add staging dokku@beta.parisleaf.com:staging
- git push staging master
addons:
  ssh_known_hosts: beta.parisleaf.com
before_install:
- openssl aes-256-cbc -K $encrypted_178fa280071e_key -iv $encrypted_178fa280071e_iv
  -in deploy_key.pem.enc -out .travis/deploy_key.pem -d
